
//admin
export const GET_LIST_COMMENT_AD = "GET_LIST_COMMENT_AD";
export const GET_DETAIL_COMMENT_AD = "GET_DETAIL_COMMENT_AD";
export const DEL_COMMENT = "DEL_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const SET_ALERT = "SET_ALERT";