export const DISPLAY_LOADING = 'DISPLAY_LOADING';
export const HIDDEN_LOADING = 'HIDDEN_LOADING';
export const TABLE_DISPLAY_LOADING = 'TABLE_DISPLAY_LOADING';
export const TABLE_HIDDEN_LOADING = 'TABLE_HIDDEN_LOADING';