export const GET_LIST_LOCATION = "GET_LIST_LOCATION";
export const GET_DETAIL_LOCATION = "GET_DETAIL_LOCATION";
//admin
export const GET_LIST_LOCATION_AD = "GET_LIST_LOCATION_AD";
export const GET_DETAIL_LOCATION_AD = "GET_DETAIL_LOCATION_AD";
export const DEL_LOCATION = "DEL_LOCATION";
export const ADD_LOCATION = "ADD_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UP_IMAGE_LOCATION = "UP_IMAGE_LOCATION";
export const SET_ALERT = "SET_ALERT";
export const GET_ALL_LOCATION = 'GET_ALL_LOCATION';
